### PR TITLE
👷 ci: add ci for tests on backend

### PR DESCRIPTION
**Pull request by LogFlames**
Add CI to automatically run tests on backend when someone pushes to main or creates a PR into main. This will make sure all code merged into main passes the test-suite.

Currently does not run mail tests as these require `gmail_token.json` file. We probably do not want it to send mail on every commit/pr as well. If we want to add these tests as well the content of `gmail_token.json` should be added under `Settings > Secrets and Variables > Action Secrets` and a step can write the secret into the `gmail_token.json` file.

A benefit of running the mail tests as well is that we would be able to run all tests. As I found no clean way of excluding the mail tests.

### CODE REVIEW

**Comment by Gabrimari** [comment]
This would be really useful, thanks a lot. I do however have some observations and questions about this.

I agree with you that we probably do not want to send mails on every commit/pr. A cleaner way to exclude the mail tests would be to introduce the test tag `"no_ci"` and using `--exclude-tag=no_ci` when running the tests. 

Setting the application URL to `"http://no-swish"` might cause problems if we in the future want to use tests that use the swish merchant simulator as this is the url swish sends their callbacks to. I am not that familiar with how running this on github actions works but is it possible to set the `APPLICATION_URL` so that swish could send their callbacks to the runner? If github allows maybe setting the `APPLICATION_URL` to the runners public ip would work. Or using the same serveo approach that is described in the Backend: Quick Start part of the wiki. Otherwise tests that utilises the swish simulator might have to be tagged with the `"no_ci"` like the mail tests. As of now the main branch does not contain any tests where this might be a problem but I imagine that we will have tests where this could be problematic in the future.

Do you have time to investigate these two points further?  

More on test tags https://docs.djangoproject.com/en/5.1/topics/testing/tools/#topics-tagging-tests
More on swish merchant simulator https://developer.swish.nu/documentation/environments#merchant-swish-simulator

**Comment by LogFlames** [comment]
Test-tags looks way cleaner, will update the pr with those

it might be possible to connect the runner to serveo and set that as the application url, I will look into it

**Comment by LogFlames** [comment]
It now runs all non no_ci-tagged tests, and exposes the url from serveo

**Comment by Gabrimari** [comment]
This is awesome! Thank you very much.

**Pull request merged**
